### ISSUE TITLE
NinjectObjectBuilderExtensions class is internal

### ISSUE THREAD

**Issue by andrewshir** [Particular/NServiceBus.Ninject#4]
## Who's affected
All users which previously defined bindings in UnitOfWork scope directly using Ninject binding syntax.

## Symptoms
Bindings cannot longer be defined using Ninject syntax, forcing users to configure UnitOfWork scope bindings with the `ConfigureComponent(...)` syntax.

--

Previously we used extensions from NinjectObjectBuilderExtensions class (especially InUnitOfWorkScope<T> method), but now it seems that class is internal and we cannot use it anymore. What should I use instead NinjectObjectBuilderExtensions in latest version?

**Comment by timbussmann** [comment]
Thanks @andrewshir for reporting this issue. We made the extensions public again with #5 which will be soon available with the 5.1.0 release.
